In [1]:
import numpy as np

## numpy的核心array 

* array本身的属性

  * shape：array各个维度的长度，返回的是一个元组

  * ndim：一个数字，表示array的维度的数目，即有几维

  * size：一个数字，表示array中所有数据元素的数目

  * dtype：array中元素的数据类型

* array本身支持的大量操作和函数

  * 直接逐元素的加减乘除等操作

  * 更好的面向多维的数组索引

  * 求sum/mean等聚合函数

  * 线性代数函数，比如求解逆矩阵、求解方程组

## 创建array的方法

* 从python的列表和嵌套列表创建array
* 使用预定函数arange、ones/ones_like、zeros/zeros_like、empty/empty_like、full/full_like、eye等函数创建
* 生成随机数的np.random模块构建

### 1.使用列表和嵌套列表创建

In [2]:
# 创建一个一维数组
x = np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 创建一个二维数组
X = np.array(
    [
        [1,2,3],
        [6,7,8]
    ]
)
X

array([[1, 2, 3],
       [6, 7, 8]])

### 2.探索数组array的属性

In [4]:
# 返回元组，各个维度的长度
x.shape

(9,)

In [5]:
# 返回元组，各个维度的长度
X.shape

(2, 3)

In [6]:
# 返回维度值
x.ndim

1

In [7]:
# 返回维度值
X.ndim

2

In [8]:
# 返回元素个数
x.size

9

In [9]:
# 返回元素个数
X.size

6

In [10]:
# array中元素的数据类型
x.dtype

dtype('int32')

In [11]:
# array中元素的数据类型
X.dtype

dtype('int32')

### 3.创建array的便捷函数

1. 使用arange创建数字序列

    * arange([start,] stop[,step], dtype=None)

In [12]:
print(np.arange(10))
print(np.arange(0, 10))
print(np.arange(1, 10))
print(np.arange(0, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


2. 使用ones创建全是1的数组

    * np.ones(shape, dtype=None, order='C')
    * shape: int or tuple of ints Shape of the new array, e.g.(2, 3) or 2.

In [13]:
print(np.ones((2,3)))
print(np.ones(10))

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3. 使用ones_like创建形状相同的数组

    * ones_like(a, dtype=float, order='C')

In [14]:
print(X.shape)
print(np.ones_like(X))

(2, 3)
[[1 1 1]
 [1 1 1]]


4. 使用zeros创建全是0的数组

    * np.zeros(shape, dtype=None, order='C')

In [15]:
print(np.zeros((2, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


5. 使用zeros_like创建形状相同的数组

    * np.zeros_like(a, dtype=float, order='C')

In [16]:
print(X.shape)
print(np.zeros_like(X))

(2, 3)
[[0 0 0]
 [0 0 0]]


6. 使用empty创建全是0的数组

    * empty(shape, dtype=float, order='C')
    
    **注意：数据是未初始化的，里面的值可能是随机值**

In [17]:
print(np.empty(10))
print(np.empty((3,4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.08309285e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.42413554e-306 1.61590357e+184 7.42883814e-091 3.93892925e-062]
 [2.38145811e+179 9.50598106e+169 3.99910963e+252 2.69817909e+184]]


7. 使用empty_like创建形状相同的数组

    * empty_like(prototype, dtype=None

In [18]:
np.empty_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

8. 使用full创建指定值的数组

    * np.full(shape, fill_value, dtype=None, order='C')

In [19]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [20]:
np.full((2,4), 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

9. 使用full_like创建形状相同的数组

    * np.full_like(a, fill_value, dtype=None)

In [21]:
np.full_like(X, 888)

array([[888, 888, 888],
       [888, 888, 888]])

10. 使用random模块生成随机数的数组

    * randn(d0, d1, ..., dn)

In [22]:
np.random.randn()

-0.48404682315653524

In [23]:
np.random.randn(3)

array([-1.11271287, -0.75270753, -1.00213555])

In [24]:
np.random.randn(3,2)

array([[-1.87843828,  0.19249163],
       [-1.34098725,  2.57404951],
       [ 0.75630435,  0.56582826]])

In [25]:
np.random.randn(3, 2, 4)

array([[[ 0.31964515,  1.49995594, -0.74978324, -2.54820092],
        [-1.8705155 , -0.77209871,  2.02695423,  0.17736428]],

       [[ 0.0713494 ,  0.44402844,  0.27918514, -0.14591187],
        [ 0.84924725, -0.16524204,  0.47679674,  2.23263787]],

       [[-0.3051885 ,  0.72560845,  0.37510042, -1.15063418],
        [-0.28971971, -0.66675259, -0.25579504,  0.36501512]]])

### 4.array本身支持的大量操作和函数

In [26]:
A = np.arange(10).reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
A.shape

(2, 5)

In [28]:
A+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
A*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [30]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [31]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [32]:
B = np.random.randn(2, 5)
B

array([[-0.16080942, -1.141154  ,  1.44880369, -2.21477453,  0.1455452 ],
       [-0.08922669, -0.40262265, -1.16051183, -0.65841758, -0.71952152]])

In [33]:
A+B

array([[-0.16080942, -0.141154  ,  3.44880369,  0.78522547,  4.1455452 ],
       [ 4.91077331,  5.59737735,  5.83948817,  7.34158242,  8.28047848]])

In [34]:
A-B

array([[0.16080942, 2.141154  , 0.55119631, 5.21477453, 3.8544548 ],
       [5.08922669, 6.40262265, 8.16051183, 8.65841758, 9.71952152]])